const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
let browser;

(async () => {
  const output = path.join(__dirname, 'screenshots');
  await fs.mkdir(output, { recursive: true });
  browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 1000 }, deviceScaleFactor: 1 });
  const settleSheet = () => page.waitForFunction(() => {
    const el = document.querySelector('.judgment-sheet[open]');
    const frame = document.querySelector('.app-surface');
    return el && frame && Number(getComputedStyle(el).opacity) >= 0.999 && el.getBoundingClientRect().bottom <= frame.getBoundingClientRect().bottom + 1;
  });
  const errors = [];
  // TDS loads optional static.toss.im icons/fonts; the restricted QA runner may
  // block those requests even though the UI has a local check-icon fallback.
  page.on('pageerror', e => { if (!e.message.includes('Failed to fetch')) errors.push(e.message); });
  page.on('requestfailed', r => console.log('REQUEST FAILED', r.url(), r.failure()?.errorText));
  await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
  await page.getByText('1,574,200원').waitFor();
  await page.screenshot({ path: path.join(output, 'desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(output, 'home.png'), fullPage: true });
  await page.getByText('가온테크', { exact: true }).click();
  await page.getByRole('button', { name: '매도', exact: true }).waitFor();
  await page.getByRole('button', { name: '수량 감소' }).click();
  await page.locator('.quick-order').getByText('76,400원', { exact: true }).waitFor();
  for (let i = 1; i < 10; i++) await page.getByRole('button', { name: '수량 증가' }).click();
  await page.getByRole('button', { name: '수량 증가' }).click();
  await page.locator('.quick-order').getByText('764,000원', { exact: true }).waitFor();
  assert(await page.getByRole('button', { name: '매수', exact: true }).isDisabled());
  assert(await page.getByRole('button', { name: '매도', exact: true }).isEnabled());
  await page.screenshot({ path: path.join(output, 'stock.png'), fullPage: true });
  await page.getByRole('button', { name: '매도', exact: true }).click();
  await page.getByText('주문을 안전하게 반영하고 있어요', { exact: true }).waitFor();
  assert(await page.getByRole('button', { name: '체결 처리 중' }).isDisabled());
  await page.getByText('성공적으로 매도가 체결되었습니다').waitFor();
  assert.equal(await page.getByRole('button', { name: '판단 저장' }).count(), 0);
  await page.getByText('판단 입력 준비 중').waitFor();
  await page.getByText('이제 판단을 남겨주세요').waitFor();
  await page.getByRole('dialog', { name: '매도 판단 남기기' }).getByRole('textbox', { name: '거래 근거' }).waitFor();
  assert(await page.getByRole('button', { name: '판단 저장' }).isDisabled());
  await page.getByRole('textbox', { name: '거래 근거' }).fill('   ');
  assert(await page.getByRole('button', { name: '판단 저장' }).isDisabled());
  await page.getByRole('textbox', { name: '거래 근거' }).fill('실적 발표 전에 수익을 확정하려고 해요.');
  await settleSheet();
  await page.getByRole('dialog', { name: '매도 판단 남기기' }).getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('textbox', { name: '거래 근거' }).waitFor({ state: 'hidden' });
  assert.equal(await page.getByText('가상 체결 완료').count(), 0);
  await page.getByRole('button', { name: '매도', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: '거래 근거' }).inputValue(), '실적 발표 전에 수익을 확정하려고 해요.');
  assert(await page.getByRole('button', { name: '판단 저장' }).isEnabled());
  await page.getByText('가온테크 10주 · 시장가 · 현재가', { exact: true }).waitFor();
  await settleSheet();
  await page.screenshot({ path: path.join(output, 'order.png'), fullPage: true });
  await page.getByRole('button', { name: '판단 저장' }).click();
  await page.getByText('가상 체결 완료').waitFor();
  await page.getByRole('button', { name: '판단 리플레이 만들기' }).click();
  await page.screenshot({ path: path.join(output, 'loading.png'), fullPage: true });
  await page.getByRole('button', { name: '판단 리플레이 확인하기' }).click({ timeout: 15000 });
  await page.getByText('같은 기간에 확인된 사실').waitFor();
  await page.screenshot({ path: path.join(output, 'review.png'), fullPage: true });
  await page.getByText('출처와 용어 보기').click();
  await page.getByText(/이 시안의 종목·거래·수급·공시는 모두 가상 예시/).waitFor();
  await page.getByRole('button', { name: '홈', exact: true }).click();
  await page.getByRole('tab', { name: '종목 찾기', exact: true }).click();
  await page.getByRole('textbox', { name: '종목 검색' }).fill('없는종목');
  await page.getByText(/검색 결과가 없어요/).waitFor();
  await page.getByRole('textbox', { name: '종목 검색' }).fill('');
  await page.getByRole('tab', { name: '판단 기록', exact: true }).click();
  await page.getByText('5월 월간 리포트', { exact: true }).click();
  await page.screenshot({ path: path.join(output, 'monthly.png'), fullPage: true });
  await page.getByRole('button', { name: '홈', exact: true }).click();
  await page.getByText('가온테크', { exact: true }).click();
  for (let i = 10; i > 7; i--) await page.getByRole('button', { name: '수량 감소' }).click();
  await page.getByRole('button', { name: '매수', exact: true }).click();
  await page.getByText('주문을 안전하게 반영하고 있어요', { exact: true }).waitFor();
  await page.getByText('성공적으로 매수가 체결되었습니다').waitFor();
  await page.getByText('판단 입력 준비 중').waitFor();
  await page.getByText('이제 판단을 남겨주세요').waitFor();
  await page.getByRole('dialog', { name: '매수 판단 남기기' }).getByRole('textbox', { name: '거래 근거' }).waitFor();
  assert.equal(await page.getByRole('textbox', { name: '거래 근거' }).inputValue(), '');
  await page.keyboard.press('Escape');
  await page.getByRole('textbox', { name: '거래 근거' }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '매수', exact: true }).click();
  for (const width of [320, 390, 1280]) {
    await page.setViewportSize({ width, height: 844 });
    await settleSheet();
    const frame = await page.locator('.app-surface').boundingBox();
    const modal = await page.locator('.judgment-sheet[open]').boundingBox();
    assert(modal && frame && modal.x >= frame.x - 1 && modal.x + modal.width <= frame.x + frame.width + 1, `Modal stays inside preview at ${width}px`);
    await page.screenshot({ path: path.join(output, `judgment-${width}.png`), fullPage: true });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('textbox', { name: '거래 근거' }).fill('다음 실적에서 반도체 장비 수요를 확인하겠어요.');
  await page.getByRole('button', { name: '판단 저장' }).click();
  await page.getByRole('button', { name: '내 기록 확인하기' }).waitFor();
  assert.equal(await page.getByRole('button', { name: '판단 리플레이 만들기' }).count(), 0);
  await page.getByRole('button', { name: '내 기록 확인하기' }).click();
  for (const width of [320, 360, 390, 736, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
    assert.equal(overflow, false, `Horizontal overflow at ${width}px`);
  }
  await browser.close();
  assert.deepEqual(errors, [], 'Browser runtime errors');
  console.log('PASS: TDS quantity stepper limits, buy/sell availability, judgment modal, cancel/Escape/draft persistence, whitespace validation, trade/replay flow, 320–1280px layout.');
})().catch(async e => { console.error(e); await browser?.close(); process.exitCode = 1; });
