const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    const out = path.join(__dirname, 'screenshots');
    await fs.mkdir(out, { recursive: true });
    await page.goto('http://127.0.0.1:5173/');
    await page.getByRole('button', { name: '토스로 시작하기', exact: true }).click();
    await page.getByRole('button', { name: '거래 기록하기', exact: true }).click();
    await page.getByRole('textbox', { name: '종목 검색' }).fill('없는종목');
    assert(await page.getByText('검색 결과가 없어요.', { exact: false }).isVisible());
    await page.getByRole('textbox', { name: '종목 검색' }).fill('가온');
    await page.getByText('가온테크', { exact: true }).click();
    await page.getByLabel('거래일', { exact: true }).fill('2026-05-10');
    assert(await page.getByText('이 날짜에는 조회 가능한 시세가 없어요.').isVisible());
    await page.getByRole('button', { name: '5월 6일', exact: true }).click();
    await page.getByLabel('평균 거래 가격', { exact: true }).fill('999999');
    await page.getByLabel('거래 수량', { exact: true }).fill('6');
    assert(await page.getByRole('button', { name: '+ 매수 기록 추가', exact: true }).isDisabled());
    await page.getByLabel('평균 거래 가격', { exact: true }).fill('70000');
    await page.getByRole('button', { name: '+ 매수 기록 추가', exact: true }).click();
    await page.getByLabel('평균 거래 가격', { exact: true }).fill('70100');
    await page.getByLabel('거래 수량', { exact: true }).fill('4');
    await page.getByRole('button', { name: '+ 매수 기록 추가', exact: true }).click();
    assert.equal(await page.locator('.trade-card').count(), 2);
    await page.getByRole('button', { name: '2번째 거래 수정', exact: true }).click();
    await page.getByLabel('거래 수량', { exact: true }).fill('3');
    await page.getByRole('button', { name: '수정 완료', exact: true }).click();
    assert.equal(await page.locator('.trade-card').count(), 2);
    await page.getByRole('button', { name: '2번째 거래 삭제', exact: true }).click();
    assert.equal(await page.locator('.trade-card').count(), 1);
    await page.getByLabel('평균 거래 가격', { exact: true }).fill('70100');
    await page.getByLabel('거래 수량', { exact: true }).fill('4');
    await page.getByRole('button', { name: '+ 매수 기록 추가', exact: true }).click();
    await page.getByRole('tab', { name: '매도', exact: true }).click();
    await page.getByRole('button', { name: '5월 29일', exact: true }).click();
    await page.getByLabel('평균 거래 가격', { exact: true }).fill('76400');
    await page.getByLabel('거래 수량', { exact: true }).fill('11');
    assert(await page.getByRole('button', { name: '+ 매도 기록 추가', exact: true }).isDisabled());
    await page.getByLabel('거래 수량', { exact: true }).fill('5');
    await page.getByRole('button', { name: '+ 매도 기록 추가', exact: true }).click();
    await page.getByRole('button', { name: '1번째 거래 삭제', exact: true }).click();
    assert.equal(await page.locator('.trade-card').count(), 3);
    await page.screenshot({ path: path.join(out, 'replay-trades.png') });
    await page.getByRole('button', { name: '거래 요약 보기 · 3건', exact: true }).click();
    assert(await page.getByText('70,040원', { exact: true }).isVisible());
    assert(await page.getByText('+32000원 (+9.1%)', { exact: true }).isVisible());
    await page.getByLabel('매수 근거', { exact: true }).fill('공시에서 실적을 확인하고 싶었어요.');
    await page.getByLabel('매도 근거', { exact: true }).fill('확인 전에 일부 수익을 확정했어요.');
    await page.screenshot({ path: path.join(out, 'replay-summary.png') });
    await page.getByRole('button', { name: 'AI 분석 시작하기', exact: true }).click();
    await page.screenshot({ path: path.join(out, 'replay-loading.png') });
    await page.getByRole('button', { name: '판단 리플레이 보기', exact: true }).click();
    assert(await page.getByText('공시에서 실적을 확인하고 싶었어요.', { exact: true }).first().isVisible());
    assert.equal(await page.locator('.benchmark').count(), 3);
    await page.screenshot({ path: path.join(out, 'replay-result.png') });
    await page.getByRole('button', { name: '내 기록으로 돌아가기', exact: true }).click();
    assert(await page.getByText('가온테크', { exact: true }).isVisible());
    await page.locator('.preview-tools > summary').click();
    await page.getByRole('button', { name: '0% 예시', exact: true }).click();
    assert.equal(await page.locator('.report-return').innerText(), '0.0%\n실현 수익률 · 0원');
    await page.getByRole('button', { name: '손실 예시', exact: true }).click();
    assert((await page.locator('.report-return').innerText()).startsWith('-8.6%'));
    assert(await page.locator('.report-return').evaluate(el => el.classList.contains('tone-blue')));
    await page.getByRole('button', { name: '자료 없음', exact: true }).last().click();
    assert(await page.getByText('시장·섹터 비교 데이터 없음', { exact: true }).isVisible());
    await page.getByRole('button', { name: '실패 예시', exact: true }).click();
    await page.getByRole('button', { name: '다시 분석하기', exact: true }).click();
    await page.getByRole('button', { name: '판단 리플레이 보기', exact: true }).click();
    await page.locator('.preview-tools > summary').click();
    await page.setViewportSize({ width: 1280, height: 1000 });
    await page.getByRole('button', { name: '수익', exact: true }).click();
    await page.screenshot({ path: path.join(out, 'replay-desktop.png') });
    for (const width of [320, 360, 390, 736, 1280]) {
      await page.setViewportSize({ width, height: 900 });
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'horizontal overflow at ' + width);
      assert(await page.locator('.app-scroll').evaluate(el => el.scrollWidth <= el.clientWidth), 'app overflow at ' + width);
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('.app-scroll').evaluate(el => { el.style.overflow = 'visible'; el.style.flex = 'none'; });
    await page.locator('.app-surface').evaluate(el => { el.style.height = 'auto'; el.style.overflow = 'visible'; });
    await page.screenshot({ path: path.join(out, 'replay-report-full.png'), fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PASS: entries, same-day splits, bounds, oversell, FIFO, reasons, loading, history, loss/zero, retry, responsive layout.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
